class ValidationError(Exception):
    pass


class NotFoundException(Exception):
    pass
